export { default as Home } from './Home'
export { default as About } from './About'
export { default as Catalog } from './Catalog'
export { default as Library } from './Library'
export { default as Login } from './Login'
export { default as Reading } from './Reading'
export { default as Register } from './Register'
export { default as Profile } from './Profile'
